[package]
edition = "2018"
name = "tui"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
crossterm = "0.21.0"
rand = "0.8.4"
serde = "1.0.130"
serde_json = "1.0.68"
tui = "0.16.0"
