[package]
edition = "2018"
name = "todo_api"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
serde = "1.0.130"
serde_json = "1.0.68"
