[package]
authors = ["daido1976 <daido1976@gmail.com>"]
edition = "2021"
name = "lsh"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.21.0"
